spring:
  datasource:
    username: jinmy
    password: 1234
    url: jdbc:mysql://localhost:3306/onlinejudge
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true
  thymeleaf:
    encoding: utf-8
    cache: false
    mode: HTML
  config:
    additional-location: com/jinmy/onlinejudge
server:
  port: 80

onlinejudge:
  root_dir: /usr/judger/
  src_dir: /usr/judger/src/
  data_dir: /usr/judger/data/
  out_dir: /usr/judger/out/
  judger_dir: /usr/lib/judger/libjudger.so
  uid: 0
  gid: 0
  judge:
    java:
      args: -Djava.security.manager -Dfile.encoding=UTF-8 -Djava.awt.headless=true Main
    python2:
      args: main.pyc
    python3:
      args: __pycache__/main.cpython-36.pyc

  compile:
    c:
      args: -DONLINE_JUDGE -O2 -w -fmax-errors=3 -std=c99 -lm
    cpp:
      args: -DONLINE_JUDGE -O2 -w -fmax-errors=3 -std=c++14 -lm
    java:
      args: -encoding UTF8
    python2:
      args: -m py_compile
    python3:
      args: -m py_compile
